-- Database Dump for hcare_db (Plaintext Schema)
-- Generated by Hcare API
-- Decrypted Schema

-- Create database if it doesn't exist
CREATE DATABASE IF NOT EXISTS `hcare_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `hcare_db`;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

-- --------------------------------------------------------

-- --------------------------------------------------------

-- Table structure for table `tenants`
DROP TABLE IF EXISTS `tenants`;
CREATE TABLE `tenants` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `domain` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `tenants` (`id`, `name`, `domain`) VALUES (1, 'Default Healthcare', 'localhost');

-- --------------------------------------------------------

-- Table structure for table `refresh_tokens`
DROP TABLE IF EXISTS `refresh_tokens`;
CREATE TABLE `refresh_tokens` (
  `id` int NOT NULL AUTO_INCREMENT,
  `token_hash` varchar(64) NOT NULL,
  `user_id` int NOT NULL,
  `expires_at` datetime NOT NULL,
  `revoked` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `token_hash` (`token_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

-- Table structure for table `users`
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` varchar(50) NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



-- --------------------------------------------------------

-- Table structure for table `patients`
DROP TABLE IF EXISTS `patients`;
CREATE TABLE `patients` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `age` int DEFAULT NULL,
  `blood_group` varchar(10) DEFAULT NULL,
  `address` text,
  `registered_date` date DEFAULT NULL,
  `medical_history` text,
  `allergies` text,
  `emergency_contact` varchar(255) DEFAULT NULL,
  `status` varchar(50) DEFAULT 'Active',
  `tenant_id` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `patients` 
(`name`, `email`, `phone`, `gender`, `age`, `blood_group`, `address`, `registered_date`, `medical_history`, `allergies`, `emergency_contact`, `status`, `tenant_id`) 
VALUES
('Arjun Kumar', 'arjun.kumar@example.com', '9876501001', 'Male', 28, 'O+', '12 MG Road, Chennai', '2025-12-01', 'None', 'None', 'Ramesh Kumar - 9876501111', 'Active', 1),
('Meenakshi R', 'meenakshi.r@example.com', '9876501002', 'Female', 25, 'A+', '34 Park Street, Coimbatore', '2025-12-02', 'Asthma', 'Pollen', 'Vijay R - 9876502222', 'Active', 1),
('Karthik V', 'karthik.v@example.com', '9876501003', 'Male', 32, 'B+', '56 Lake Road, Madurai', '2025-12-03', 'Diabetes', 'Sulfa Drugs', 'Aravind V - 9876503333', 'Active', 1),
('Divya S', 'divya.s@example.com', '9876501004', 'Female', 27, 'AB+', '78 Hill Street, Salem', '2025-12-04', 'None', 'None', 'Rohini S - 9876504444', 'Active', 1),
('Praveen M', 'praveen.m@example.com', '9876501005', 'Male', 35, 'O-', '90 River Lane, Tiruchirappalli', '2025-12-05', 'Hypertension', 'Penicillin', 'Sahana M - 9876505555', 'Active', 1),
('Nithya P', 'nithya.p@example.com', '9876501006', 'Female', 26, 'A-', '102 Garden Street, Erode', '2025-12-06', 'None', 'Nuts', 'Karthik P - 9876506666', 'Active', 1),
('Suresh K', 'suresh.k@example.com', '9876501007', 'Male', 31, 'B-', '114 Ocean Road, Vellore', '2025-12-07', 'Asthma', 'Dust', 'Mani K - 9876507777', 'Active', 1),
('Lakshmi T', 'lakshmi.t@example.com', '9876501008', 'Female', 24, 'AB-', '126 Sunset Boulevard, Thanjavur', '2025-12-08', 'None', 'None', 'Priya T - 9876508888', 'Active', 1),
('Ravi R', 'ravi.r@example.com', '9876501009', 'Male', 33, 'O+', '138 Palm Street, Tirunelveli', '2025-12-09', 'Allergy to dust', 'Dust', 'Kumar R - 9876509999', 'Active', 1),
('Anitha N', 'anitha.n@example.com', '9876501010', 'Female', 29, 'A+', '150 Rose Avenue, Madurai', '2025-12-10', 'None', 'Penicillin', 'Rahul N - 9876510000', 'Active', 1);


-- --------------------------------------------------------

-- Table structure for table `doctors`
DROP TABLE IF EXISTS `doctors`;
CREATE TABLE `doctors` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `age` int DEFAULT NULL,
  `specialization` varchar(255) DEFAULT NULL,
  `qualification` varchar(255) DEFAULT NULL,
  `experience` varchar(255) DEFAULT NULL,
  `contact` varchar(50) DEFAULT NULL,
  `address` text,
  `available_days` text,
  `available_time` varchar(255) DEFAULT NULL,
  `status` varchar(50) DEFAULT 'Active',
  `department` varchar(255) DEFAULT NULL,
  `license_number` varchar(100) DEFAULT NULL,
  `rating` double DEFAULT '0',
  `consultation_fee` decimal(10,2) DEFAULT '0.00',
  `bio` text,
  `tenant_id` int DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `doctors` 
(`name`, `email`, `gender`, `age`, `specialization`, `qualification`, `experience`, `contact`, `address`, `available_days`, `available_time`, `status`, `department`, `license_number`, `rating`, `consultation_fee`, `bio`, `tenant_id`) 
VALUES
('Dr. Aravind Kumar', 'aravind.kumar@hospital.com', 'Male', 45, 'Cardiologist', 'MBBS, MD', '20 years', '9876510001', '12 MG Road, Chennai', 'Mon,Tue,Thu', '09:00-14:00', 'Active', 'Cardiology', 'TN12345', 4.8, 1500.00, 'Expert in cardiac surgery and patient care.', 1),
('Dr. Meenakshi R', 'meenakshi.r@hospital.com', 'Female', 38, 'Gynecologist', 'MBBS, DGO', '12 years', '9876510002', '34 Park Street, Coimbatore', 'Mon,Wed,Fri', '10:00-16:00', 'Active', 'Gynecology', 'TN12346', 4.6, 1200.00, 'Specialist in women health and maternity care.', 1),
('Dr. Karthik V', 'karthik.v@hospital.com', 'Male', 42, 'Orthopedic', 'MBBS, MS', '15 years', '9876510003', '56 Lake Road, Madurai', 'Tue,Thu,Sat', '09:00-15:00', 'Active', 'Orthopedics', 'TN12347', 4.7, 1300.00, 'Experienced in joint replacement and fracture treatment.', 1),
('Dr. Divya S', 'divya.s@hospital.com', 'Female', 35, 'Pediatrician', 'MBBS, DCH', '10 years', '9876510004', '78 Hill Street, Salem', 'Mon-Fri', '09:00-13:00', 'Active', 'Pediatrics', 'TN12348', 4.5, 1000.00, 'Focused on child health and vaccinations.', 1),
('Dr. Praveen M', 'praveen.m@hospital.com', 'Male', 50, 'Neurologist', 'MBBS, DM', '25 years', '9876510005', '90 River Lane, Tiruchirappalli', 'Mon,Wed,Fri', '11:00-16:00', 'Active', 'Neurology', 'TN12349', 4.9, 1800.00, 'Specialist in neurological disorders and treatments.', 1),
('Dr. Nithya P', 'nithya.p@hospital.com', 'Female', 37, 'Dermatologist', 'MBBS, DDV', '13 years', '9876510006', '102 Garden Street, Erode', 'Tue,Thu', '10:00-14:00', 'Active', 'Dermatology', 'TN12350', 4.6, 1100.00, 'Expert in skin diseases and cosmetic dermatology.', 1),
('Dr. Suresh K', 'suresh.k@hospital.com', 'Male', 40, 'ENT Specialist', 'MBBS, MS', '15 years', '9876510007', '114 Ocean Road, Vellore', 'Mon,Wed,Fri', '09:00-14:00', 'Active', 'ENT', 'TN12351', 4.7, 1200.00, 'Specialist in ENT treatments and surgeries.', 1),
('Dr. Lakshmi T', 'lakshmi.t@hospital.com', 'Female', 36, 'Ophthalmologist', 'MBBS, DO', '12 years', '9876510008', '126 Sunset Boulevard, Thanjavur', 'Mon-Fri', '09:00-15:00', 'Active', 'Ophthalmology', 'TN12352', 4.5, 1100.00, 'Expert in eye care and vision correction.', 1),
('Dr. Ravi R', 'ravi.r@hospital.com', 'Male', 44, 'General Surgeon', 'MBBS, MS', '18 years', '9876510009', '138 Palm Street, Tirunelveli', 'Tue,Thu,Sat', '09:00-15:00', 'Active', 'Surgery', 'TN12353', 4.8, 1400.00, 'Experienced in general surgeries and emergency care.', 1),
('Dr. Anitha N', 'anitha.n@hospital.com', 'Female', 39, 'Psychiatrist', 'MBBS, MD', '14 years', '9876510010', '150 Rose Avenue, Madurai', 'Mon,Wed,Fri', '10:00-16:00', 'Active', 'Psychiatry', 'TN12354', 4.6, 1300.00, 'Specialist in mental health and counseling.', 1);


-- --------------------------------------------------------

-- Table structure for table `appointments`
DROP TABLE IF EXISTS `appointments`;
CREATE TABLE `appointments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `patient_id` int NOT NULL,
  `doctor_id` int NOT NULL,
  `appointment_date` date NOT NULL,
  `appointment_time` time NOT NULL,
  `reason` text,
  `status` varchar(50) DEFAULT 'Pending',
  `payment_amount` decimal(10,2) DEFAULT '0.00',
  `notes` text,
  `tenant_id` int DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

-- Table structure for table `nurses`
DROP TABLE IF EXISTS `nurses`;
CREATE TABLE `nurses` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `age` int DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `department` varchar(255) DEFAULT NULL,
  `shift` varchar(50) DEFAULT NULL,
  `experience` varchar(255) DEFAULT NULL,
  `status` varchar(50) DEFAULT 'Active',
  `tenant_id` int DEFAULT NULL,
  `date_joined` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `nurses` 
(`name`, `email`, `gender`, `age`, `phone`, `department`, `shift`, `experience`, `status`, `tenant_id`, `date_joined`) 
VALUES
('Priya S', 'priya.s@nurses.com', 'Female', 28, '9876521001', 'Cardiology', 'Morning', '5 years', 'Active', 1, '2023-01-10'),
('Anjali R', 'anjali.r@nurses.com', 'Female', 32, '9876521002', 'Gynecology', 'Evening', '8 years', 'Active', 1, '2022-05-15'),
('Karthik M', 'karthik.m@nurses.com', 'Male', 30, '9876521003', 'Orthopedics', 'Night', '6 years', 'Active', 1, '2021-11-20');

-- --------------------------------------------------------

-- Table structure for table `pharmacists`
DROP TABLE IF EXISTS `pharmacists`;
CREATE TABLE `pharmacists` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `license_no` varchar(100) DEFAULT NULL,
  `contact` varchar(50) DEFAULT NULL,
  `experience` varchar(255) DEFAULT NULL,
  `status` varchar(50) DEFAULT 'Active',
  `tenant_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `pharmacists` 
(`name`, `email`, `license_no`, `contact`, `experience`, `status`, `tenant_id`) 
VALUES
('Arun R', 'arun.r@pharmacy.com', 'TNPH001', '9876542001', '7 years', 'Active', 1),
('Nithya S', 'nithya.s@pharmacy.com', 'TNPH002', '9876542002', '5 years', 'Active', 1);


-- --------------------------------------------------------

-- Table structure for table `receptionists`
DROP TABLE IF EXISTS `receptionists`;
CREATE TABLE `receptionists` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `shift` varchar(50) DEFAULT NULL,
  `contact` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT 'Active',
  `tenant_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `receptionists` 
(`name`, `email`, `shift`, `contact`, `status`, `tenant_id`) 
VALUES
('Divya S', 'divya.s@reception.com', 'Morning', '9876531001', 'Active', 1),
('Ramesh K', 'ramesh.k@reception.com', 'Evening', '9876531002', 'Active', 1);


-- --------------------------------------------------------

-- Table structure for table `medicines`
DROP TABLE IF EXISTS `medicines`;
CREATE TABLE `medicines` (
  `id` int NOT NULL AUTO_INCREMENT,
  `medicine_name` varchar(255) NOT NULL,
  `description` text,
  `category` varchar(100) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT '0.00',
  `stock` int DEFAULT '0',
  `expiry_date` date DEFAULT NULL,
  `tenant_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

-- Table structure for table `invoices`
DROP TABLE IF EXISTS `invoices`;
CREATE TABLE `invoices` (
  `id` int NOT NULL AUTO_INCREMENT,
  `invoice_date` date NOT NULL,
  `patient_id` int NOT NULL,
  `doctor_id` int DEFAULT NULL,
  `total_amount` decimal(10,2) DEFAULT '0.00',
  `paid_amount` decimal(10,2) DEFAULT '0.00',
  `status` varchar(50) DEFAULT 'Unpaid',
  `tenant_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------
-- Sample data for `medicines` table
INSERT INTO `medicines` (`medicine_name`, `description`, `category`, `price`, `stock`, `expiry_date`, `tenant_id`) VALUES
('Paracetamol 500mg', 'Pain reliever and fever reducer', 'Analgesic', 20.00, 150, '2026-12-31', 1),
('Amoxicillin 250mg', 'Antibiotic for bacterial infections', 'Antibiotic', 35.00, 100, '2025-11-30', 1),
('Cough Syrup', 'Relieves cough and throat irritation', 'Cough & Cold', 45.50, 80, '2026-06-30', 1),
('Cetirizine 10mg', 'Antihistamine for allergy relief', 'Allergy', 15.00, 200, '2027-01-15', 1),
('Metformin 500mg', 'Used to treat type 2 diabetes', 'Diabetes', 50.00, 120, '2025-09-30', 1),
('Vitamin D3 1000 IU', 'Supports bone health', 'Supplement', 25.00, 90, '2026-08-31', 1),
('Omeprazole 20mg', 'Reduces stomach acid', 'Gastrointestinal', 40.00, 60, '2025-12-31', 1),
('Azithromycin 500mg', 'Antibiotic for infections', 'Antibiotic', 80.00, 70, '2025-10-31', 1),
('Ibuprofen 400mg', 'Pain reliever and anti-inflammatory', 'Analgesic', 30.00, 110, '2026-03-31', 1),
('Ranitidine 150mg', 'Reduces stomach acid', 'Gastrointestinal', 28.00, 95, '2025-11-30', 1);


-- --------------------------------------------------------

-- Table structure for table `prescriptions`
DROP TABLE IF EXISTS `prescriptions`;
CREATE TABLE `prescriptions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `patient_id` int NOT NULL,
  `doctor_id` int NOT NULL,
  `appointment_id` int DEFAULT NULL,
  `pharmacist_id` int DEFAULT NULL,
  `medicines` text, 
  `dosage` text,
  `instructions` text,
  `notes` text,
  `status` varchar(50) DEFAULT 'Pending',
  `prescription_date` date DEFAULT NULL,
  `tenant_id` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `patient_id` (`patient_id`),
  KEY `doctor_id` (`doctor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

-- Table structure for table `notifications`
DROP TABLE IF EXISTS `notifications`;
CREATE TABLE `notifications` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `message` text NOT NULL,
  `read_status` tinyint(1) DEFAULT '0',
  `tenant_id` int DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

-- Table structure for table `news`
DROP TABLE IF EXISTS `news`;
CREATE TABLE `news` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `content` text,
  `published_date` date DEFAULT NULL,
  `tenant_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

-- Table structure for table `billing`
DROP TABLE IF EXISTS `billing`;
CREATE TABLE `billing` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `amount` decimal(10,2) DEFAULT '0.00',
  `date` date DEFAULT NULL,
  `tenant_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for table `communication_notes`
DROP TABLE IF EXISTS `communication_notes`;
CREATE TABLE `communication_notes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `appointment_id` int NOT NULL,
  `sender_id` int NOT NULL,
  `sender_role` varchar(50) NOT NULL,
  `content` text NOT NULL,
  `tenant_id` int NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `appointment_id` (`appointment_id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `sender_id` (`sender_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

COMMIT;
